name: CI/CD

on:
  push:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  deploy:    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        ref: caprover-releases
    
    - name: Set captain-definition new image
      uses: jossef/action-set-json-field@v1
      with:
        file: captain-definition
        field: imageName
        value: ${{secrets.DOCKER_USER}}/picsize-test-api:${{ github.run_id }}
